//Azriel Bachrach
//September 3 2020
//Intro to CS

public class Animation 
{
    public static void main(String[] args) throws InterruptedException 
    {
        System.out.println("\u001b[2J" + "\u001b[?25l");

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              o              |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);
        
        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                   /         |");
        System.out.println("|              |   /          |");
        System.out.println("|              |  /           |");
        System.out.println("|              | /            |");
        System.out.println("|              o              |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);
 
        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              o ----------   |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              o              |");
        System.out.println("|               \\             |");
        System.out.println("|                \\            |");
        System.out.println("|                 \\           |");
        System.out.println("|                  \\          |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              o              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              o              |");
        System.out.println("|             /               |");
        System.out.println("|            /                |");
        System.out.println("|           /                 |");
        System.out.println("|          /                  |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|   ---------- o              |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|         \\                   |");
        System.out.println("|          \\   |              |");
        System.out.println("|           \\  |              |");
        System.out.println("|            \\ |              |");
        System.out.println("|              o              |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println("\u0007");
        System.out.println("-------------------------------");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |  /           |");
        System.out.println("|              | /            |");
        System.out.println("|              o              |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                   /         |");
        System.out.println("|                  /          |");
        System.out.println("|                 /           |");
        System.out.println("|                /            |");
        System.out.println("|              o              |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);
 
        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                 /           |");
        System.out.println("|                /            |");
        System.out.println("|              o ----------   |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);
 
        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                 /           |");
        System.out.println("|                /            |");
        System.out.println("|              o              |");
        System.out.println("|               \\             |");
        System.out.println("|                \\            |");
        System.out.println("|                 \\           |");
        System.out.println("|                  \\          |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);


        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                 /           |");
        System.out.println("|                /            |");
        System.out.println("|              o              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                 /           |");
        System.out.println("|                /            |");
        System.out.println("|              o              |");
        System.out.println("|             /               |");
        System.out.println("|            /                |");
        System.out.println("|           /                 |");
        System.out.println("|          /                  |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                 /           |");
        System.out.println("|                /            |");
        System.out.println("|   ---------- o              |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|         \\                   |");
        System.out.println("|          \\                  |");
        System.out.println("|           \\     /           |");
        System.out.println("|            \\   /            |");
        System.out.println("|              o              |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println("\u0007");
        System.out.println("-------------------------------");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              o ------       |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                   /         |");
        System.out.println("|                  /          |");
        System.out.println("|                 /           |");
        System.out.println("|                /            |");
        System.out.println("|              o ------       |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);
 
        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|              o ----------   |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|              o ------       |");
        System.out.println("|               \\             |");
        System.out.println("|                \\            |");
        System.out.println("|                 \\           |");
        System.out.println("|                  \\          |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|              o ------       |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|              o ------       |");
        System.out.println("|             /               |");
        System.out.println("|            /                |");
        System.out.println("|           /                 |");
        System.out.println("|          /                  |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|   ---------- o ------       |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println();
        System.out.println("-------------------------------");
        System.out.println("|                             |");
        System.out.println("|         \\                   |");
        System.out.println("|          \\                  |");
        System.out.println("|           \\                 |");
        System.out.println("|            \\                |");
        System.out.println("|              o ------       |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);

        System.out.println("\u001b[H");
        System.out.println("\u0007");
        System.out.println("-------------------------------");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              |              |");
        System.out.println("|              o              |");
        System.out.println("|               \\             |");
        System.out.println("|                \\            |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("|                             |");
        System.out.println("-------------------------------");
        Thread.sleep(150);


        System.out.println("\u001b[?25h");
    }
}
